version: '3'

services:
  app:
    build:
      context: app
      dockerfile: Dockerfile
    ports:
      - "3334:3333"

    #links:
    #  - sorter
  sorter:
    build:
      context: app
      dockerfile: Dockerfile
    environment :
      - b
    ports:
      - "3333:3333"
    depends_on:
      - app
    links:
      - app
  
